drop: Replace neo_dir from /opt/neo/release/2020.10.05 to /usr
The libze_loader in the older neo dir on anfed was causing a linking
issue complaining about undefined reference to tozeDriverGetExtensionFunctionAddress.
This fix updates neo_dir to /usr to avoid using the libze_loader from
the older neo dir. Additionally, LDFLAGS were reordered to make sure that
libfabric libs are picked from the custom path instead of /usr.